config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :pages, only: :home
  resources :categories, only: :index do
    resources :items do
      resources :reviews, only: [:create, :update, :destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy
  belongs_to :category, optional: true
  validates :label, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews, dependent: :destroy

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :reviews, dependent: :destroy

  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
   # before_action :configure_permitted_parameters, if: :devise_controller?

    #private
    #def configure_permitted_parameters
      #devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    #end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  private

  def category_params
    params.require(:category).permit(:label)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :destroy]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def show
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to item_path(@item)
    else
     render :new
    end
  end

  def edit
  end

  def update
    @item.update(item_params)
    redirect_to item_path(@item)
  end

  def destroy
    @item.destroy
    redirect_to item_path(@item)
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :description, :address, :phone, :price, :date_start, :date_end)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:new, :create, :edit , :destroy]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.item = @item
    @review.user = current_user
    if @review.save!
      redirect_to item_path(@item), notice: "review saved!"
    else
      render 'items/show'
    end
  end

  def edit
  end

  def destroy
    @review.destroy
    redirect_to item_path(@item)
  end

  private

  def set_review
    @item = Item.find(params[:item_id])
  end

  def comment_params
    params.require(:reviews).permit(:comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<!--<div class="logo">
  <%= image_tag("logo_test.png", class: "logo")%>
</div>-->

<div class="container">
  <% @categories.first(5).each do |category| %>

    <div class="card-categorie">
      <div class="card-image">
        <%= link_to categories_path(category) do %>
        <% end %>
      </div>
      <div class="category-name">
        <%if foreign_key = nil %>
          <li><h3><%=category.label %></h3></li>
        <% end %>
      </div>
    </div>

  <% end %>
</div>

app/views/items/index.html.erb
<%= render 'shared/footer'%>
<div class="logo">
  <%= image_tag("logo_test.png", class: "logo")%>
</div>

app/views/items/new.html.erb
<div class="container">
  <h1 class="text-center mt-3">Ajouter du contenu</h1>
  <div class="row">
    <div class="col-12">
      <div class="form">
        <%= simple_form_for (@item) do |f|%>
        <%= f.input :category, label: "Categorie"%>
        <%= f.input :category, label: "Sous-categorie"%>
        <%= f.input :name, label: "titre"%>
        <%= f.input :description%>
        <%= f.input :address, label: "Adresse"%>
        <%= f.input :date_start, label: "Date début"%>
        <%= f.input :date_end, label: "Date fin"%>
        <%= f.input :price, label: "Prix"%>
        <%= f.input :photo, as: :file %>
        <%= f.submit "Envoyer", class: "button-submit"%>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QueerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,500;0,700;1,100;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <!--<%= render 'shared/footer'%>-->


    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-home">
  <div class="logo-homepage">
    <%= image_tag("logo_test.png", class: "logo-home")%>
  </div>
  <br>
  <div class="content">
    <div class="text">
      <p>L'app pour trouver ce que tu cherches et informer celleux qui cherchent!!</p>
    </div>
    <div class="link">
      <a class="button-ajout" href="/items/new">Ajouter du contenu</a>
      <p><%= link_to "ENTRER", categories_path, class:"btn btn-warning " %></p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer" style = "left: 0px; right: 0px">
    <a href="/"><i class="fa-solid fa-house"></i></a>
    <a href="/dashboard"><i class="fa-solid fa-user"></i></a>
</div>

app/views/shared/_navbar.html.erb
<!--<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "logo_test.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>-->

<div class="navbar">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag("logo_test.png", class: "logo")%>
    <% end %>
  </div>
  <div class="titre">
    <% if %>
      <h2></h2>
    <% end %>
  </div>
</div>